services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs

    depends_on:
      - frontend
      - backend1
      - backend2
      - backend3

  frontend:
    build: ./frontend
    expose:
      - "3000"
  
  backend1:
    build: ./backend
    expose:
      - "5555"

  backend2:
    build: ./backend
    expose: 
      - "5555"
 
  backend3:
     build: ./backend
     expose:
       - "5555"
