

name: Docker CI

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME : ${{ vars.DOCKER_USERNAME }}

    steps:
      - name : Checkout Repository
        uses : actions/checkout@v4
      
      - name : Login to DockerHub
        uses : docker/login-action@v3
        with : 
           username : $DOCKER_USERNAME
           password : ${{ secrets.DOCKER_PASSWORD }}

      - name : Build Backend
        run : |
          docker build \
            -t $DOCKER_USERNAME/backend:${{ github.sha }} \
            -t $DOCKER_USERNAME/backend:latest \
            ./backend

      - name : Build Frontend 
        run : |
          docker build \
          -t $DOCKER_USERNAME/frontend:${{ github.sha }} \
          -t $DOCKER_USERNAME/frontend:latest \
          ./frontend

      - name : Push Backend
        run : |
            docker push $DOCKER_USERNAME/backend:${{ github.sha }}
            docker push $DOCKER_USERNAME/backend:latest

      - name : Push Frontend
        run : |
            docker push $DOCKER_USERNAME/frontend:${{ github.sha }}
            docker push $DOCKER_USERNAME/frontend:latest

      - name : Deploy
        uses : appleboy/ssh-action@v1.2.0

        with : 
          host : ${{ secrets.SERVER_IP }}
          username : ${{ secrets.SERVER_USER }}
          key : ${{ secrets.PRIVATE_KEY }}

          script: |
            cd /home/rakesh/Desktop/practices/nginx/fullstack_app/

            docker compose pull

            docker compose up -d




      